global:
  scrape_interval: 5s # Scrape all endpoints we configure every 5 seconds.

# prometheus is a metrics aggregator

scrape_configs:
  - job_name: 'patient-service'
    metrics_path: 'actuator/prometheus'
    static_configs:
      - targets: ['patient-service:4000']





# http://localhost:9090