spring.application.name=patient-service

#spring.h2.console.path=/h2-console
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driver-class-name=org.h2.Driver
#
#spring.datasource.username=admin
#spring.datasource.password=password
#
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.jpa.hibernate.ddl-auto=update

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.ByteArraySerializer

server.port=4000

logging.level.root = INFO

resilience4j.circuitbreaker.instances.billingService.slidingWindowSize = 10
# evaluate the last 10 calls to determine if the circuit is open or closed
resilience4j.circuitbreaker.instances.billingService.minimumNumberOfCalls = 5
# there must be at least 5 calls before calculating the failure rate
resilience4j.circuitbreaker.instances.billingService.failureRateThreshold = 50
# Percentage of calls that must fail before opening the circuit, start triggering the fallback method
resilience4j.circuitbreaker.instances.billingService.waitDurationInOpenState = 10s
# Keep the circuit open for 10 seconds before trying again for recovery
resilience4j.circuitbreaker.instances.billingService.permittedNumberOfCallsInHalfOpenState = 3
# We want to make 3 trial calls in a half-open state to check recovery
resilience4j.circuitbreaker.instances.billingService.automaticTransitionFromOpenToHalfOpenEnabled = true
# don't wait for a new request, just Automatically move from open to half-open state after circuit breaks deems its safe to do so

resilience4j.retry.instances.billingRetry.maxAttempts=2
# try at least 2 times to call the billing service
resilience4j.retry.instances.billingRetry.waitDuration=500ms
# retry twice and wait for half a second and then handover to the circuit breaker


# Specify metrics that we want to expose
management.endpoints.web.exposure.include=health,info,prometheus,metrics,cache
# unrestricted access to prometheus because app and prometheus in the same network
management.endpoint.prometheus.access=unrestricted
management.prometheus.metrics.export.enabled=true

# http://localhost:4000/actuator/prometheus
# http://localhost:4000/actuator/metrics